# -*- coding: utf-8 -*-
"""Final Trained Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sMMGYN7GsZrCjdd3t4k1dBUXd1CW5rwp
"""

# This is the FINAL script that loads your combined, cleaned feature data,
# trains the Random Forest Classifier, and saves the final model file.

import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import os

# --- 1. CONFIGURATION AND DATA PATHS ---

# !!! CRITICAL: Set this path to your final, merged CSV file !!!
# This file MUST contain the 5 feature columns, the 'Condition' label, and the 'test_id'.
DATA_FILEPATH = '/content/Voice_and_Gait_merged.csv'
MODEL_OUTPUT_PATH = './multimodal_pd_detector.joblib'

# --- 2. DATA LOADING ---

def load_multimodal_data():
    """
    Loads the final, merged CSV file containing all features and the target label.
    """
    print(f"Attempting to load data from: {DATA_FILEPATH}")

    if not os.path.exists(DATA_FILEPATH):
        print(f"\nFATAL ERROR: Data file not found at {DATA_FILEPATH}")
        print("Please check the DATA_FILEPATH variable and ensure the CSV is in the correct location.")
        return pd.DataFrame() # Return empty DataFrame on failure

    df = pd.read_csv(DATA_FILEPATH)

    # Ensure the required columns are present after loading
    required_cols = ['Cadence_steps_per_min', 'Stride_Length_m', 'Gait_Variability_SD',
                     'Jitter_percent', 'Shimmer_percent', 'Condition']

    missing_cols = [col for col in required_cols if col not in df.columns]

    if missing_cols:
        print(f"\nFATAL ERROR: Missing required features in the CSV: {missing_cols}")
        print(f"Available columns: {list(df.columns)}")
        return pd.DataFrame()

    print(f"Successfully loaded {len(df)} multimodal samples.")
    print("Features ready for training.")
    return df


# --- 3. MODEL TRAINING AND EVALUATION ---

def train_multimodal_model(df):
    """Trains a Random Forest Classifier on the combined dataset."""

    # Identify features (X) and target (y)
    # Drop test_id (if present) as it is an identifier, not a feature

    # List of all feature columns (5 features)
    feature_cols = ['Cadence_steps_per_min', 'Stride_Length_m', 'Gait_Variability_SD',
                    'Jitter_percent', 'Shimmer_percent']

    X = df[feature_cols]
    y = df['Condition']

    # --- Data Splitting ---
    # Split the data into 75% for training and 25% for testing
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.25,
        random_state=42,
        stratify=y # Ensures an equal mix of PD and HC in both sets
    )

    # Initialize and Train the Random Forest Classifier
    print("\nTraining Multimodal Random Forest Classifier...")
    model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced') # Use class_weight for slightly better handling of class imbalance
    model.fit(X_train, y_train)

    # --- Evaluation ---
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    print("\n--- Model Training Results ---")
    print(f"Accuracy: {accuracy:.4f}")
    print("\nClassification Report (PD vs HC):")
    print(classification_report(y_test, y_pred, target_names=['HC', 'PD']))

    # --- Saving the Model ---
    joblib.dump(model, MODEL_OUTPUT_PATH)
    print(f"\nSUCCESS: Trained model saved to {MODEL_OUTPUT_PATH}")
    print("-" * 30)

    # Output the list of features the model was trained on
    print("\nFeatures used for training (in order):")
    print(list(feature_cols))


# --- 4. EXECUTION ---

if __name__ == "__main__":

    # Step 1: Load the combined feature file
    multimodal_data = load_multimodal_data()

    if not multimodal_data.empty:
        # Step 2: Train the model on the combined data
        train_multimodal_model(multimodal_data)
    else:
        print("\nTraining aborted due to data loading failure.")